[tox]
envlist = py310, py311, py312
isolated_build = true

[testenv]
description = Run tests with pytest
deps =
    -e {toxinidir}[dev]
commands =
    ruff check src/
    ruff format --check src/
    pytest {posargs}

[testenv:py310]
base_python = python3.10

[testenv:py311]
base_python = python3.11

[testenv:py312]
base_python = python3.12

